# Generated by Django 4.1.1 on 2022-10-23 20:23

from django.db import migrations
from django.contrib.auth.models import Group


class Migration(migrations.Migration):

    def create_groups(self, schema_editor):
        GROUPS = ['admin', 'client',
                  'seguradora_managers', 'delegacao_managers']

        for group in GROUPS:
            Group.objects.get_or_create(name=group)

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
