# Generated by Django 4.1.1 on 2022-10-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
