# Generated by Django 4.1.1 on 2022-10-23 21:21

from django.db import migrations
from django.shortcuts import get_object_or_404
from authentication.serializers import UsersSerializer
from authentication.models import User
from django.contrib.auth.models import Group


class Migration(migrations.Migration):

    def create_admin(self, schema_editor):
        admin_data = {
            "username": "admin",
            "password": "melvinnunes",
            "first_name": "Melvin Nunes",
            "last_name": "Fuu",
            "email": "melvinlinho@gmail.com",
            "birth_date": "2001-01-01",
            "contact_1": "8424885656",
            "contact_2": "8465686868",
            "contact_3": "49947897",
            "address": "Av eduardo mondlane n 2525"
        }
        serializer_user = UsersSerializer(data=admin_data)
        total_users = User.objects.all().count()
        if total_users <= 0:
            if serializer_user.is_valid(raise_exception=True):
                password = serializer_user.validated_data.pop('password', None)
                instance = serializer_user.save()
                if password is not None:
                    instance.set_password(password)
                    username = serializer_user.validated_data.get('username')
                    obj = get_object_or_404(User, username=username)
                    instance.owner = obj
                    instance.is_superuser = True
                    g = Group.objects.get(name='admin')
                    instance.groups.add(g)
                    instance.save()
                    serializer_user.save()

    dependencies = [
        ('authentication', '0004_alter_user_contact_1_alter_user_contact_2_and_more'),
    ]

    operations = [
        migrations.RunPython(create_admin)
    ]
